spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/HotelBooking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    baseline-on-migrate: true
    enabled: false
    user: postgres
    password: password

jwt:
  secret: b64r9mCtI4x3aLkKjpM7K7Q6w7I6Z4pHxu1b8G8Hw2M9sV5fY3jR2uN1wW6tA0pP4oQ2vN5xY2zT8kI1gX3rF7yM2bT0oH1zR9a
  expired-time: 36000000