spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/HotelBooking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    baseline-on-migrate: true
    enabled: false
    user: postgres
    password: password